[workspace]
resolver = "2"
members = [
    "cubestore",
    "cubestore-sql-tests",
    "cubehll",
    "cubezetasketch",
    "cuberpc",
]

[patch."https://github.com/cube-js/sqlparser-rs.git"]
sqlparser = { git = "https://github.com/cube-js//sqlparser-rs.git", branch = "part-ind" }
